---
ID: "a83c7081-c680-5d14-9dfd-bf2844afb047"
Parent: "9e12db9b-2e38-5d79-bdb1-c75fa073f762"
Template: "9e12db9b-2e38-5d79-bdb1-c75fa073f762"
Path: "/sitecore/templates/Project/jss/Styleguide-ItemLink-Item-Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210415T010546Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4350cb5e-aecb-4b41-bc84-bdb05c20bceb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210415T010546Z
