---
ID: "2c58af6c-19f6-5651-bb8c-41b51b29687f"
Parent: "72d3fb59-af3b-5454-8bc1-105b5e5b7db8"
Template: "72d3fb59-af3b-5454-8bc1-105b5e5b7db8"
Path: "/sitecore/templates/Project/jss/Styleguide-FieldUsage-File/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210415T010550Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0e3426fd-913e-4849-adc7-6c88d26a70c4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210415T010550Z
